# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

per_cell_qc <- function(matrix, featcon, top, limit) {
    .Call(`_scuttle_per_cell_qc`, matrix, featcon, top, limit)
}

per_feature_qc <- function(matrix, cellcon, limit) {
    .Call(`_scuttle_per_feature_qc`, matrix, cellcon, limit)
}

top_cumprop <- function(matrix, top) {
    .Call(`_scuttle_top_cumprop`, matrix, top)
}

downsample_column <- function(input, prop) {
    .Call(`_scuttle_downsample_column`, input, prop)
}

downsample_matrix <- function(rmat, total, prop) {
    .Call(`_scuttle_downsample_matrix`, rmat, total, prop)
}

sum_row_counts <- function(counts, genes, runs) {
    .Call(`_scuttle_sum_row_counts`, counts, genes, runs)
}

